:: DO NOT PUSH to any repository
:: This is a sample file to store your secret keys

SET MLFLOW_EXPERIMENT_ID="REPLACE_WITH_YOUR_MLFLOW_EXPERIMENT_ID"
SET MLFLOW_TRACKING_URI="REPLACE_WITH_YOUR_MLFLOW_TRACKING_URI";
SET AWS_ACCESS_KEY_ID="REPLACE_WITH_YOUR_AWS_ACCESS_KEY_ID";
SET AWS_SECRET_ACCESS_KEY="REPLACE_WITH_YOUR_AWS_SECRET_ACCESS_KEY";
SET BACKEND_STORE_URI="REPLACE_WITH_YOUR_BACKEND_STORE_URI";
SET ARTIFACT_ROOT="REPLACE_WITH_YOUR_ARTIFACT_ROOT";